### ISSUE TITLE
error on line 966, in generate_frag_cas_guess

### ISSUE THREAD

**Issue by SinaChini** [MatthewRHermes/mrh#1]
full error decription:
  File "lasscf_calc.py", line 102, in <module>
    me2n2_dmet.generate_frag_cas_guess (mf, CASlist)
  File "/panfs/roc/groups/0/cramercj/chini006/mrh/my_dmet/main_object.py", line 966, in generate_frag_cas_guess
    amo_new_coeff = np.append (mo_coeff[:,ncore_target:ncore_current], mo_coeff[:,nocc_current:nocc_target], axis=1)
TypeError: 'RHF' object is not subscriptable

Thanks,
Sina

**Comment by MatthewRHermes** [comment]
That is not a bug in generate_frag_cas_guess, that is a bug in lasscf_calc.py.  Is that one of the example scripts?  I'm sorry, I haven't gotten around to fixing them yet.  But generate_frag_cas_guess should be passed with mf.mo_coeff, not mf.  It's the same as the problem with your DNA calculation from earlier.
