### ISSUE TITLE
Problems in LASSCF orbital optimization 

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#110]
FYI: With the new implementation, the LASSCF orb optimization is  facing SVD non-convergence problems. All of these optimization were done with previous LASSCF very smoothly. 

Abby is also facing same problem with some other complexes.

 File "/project/lgagliardi/jangidbhavnesh/Apps/Trash/newdev/mrh/my_pyscf/mcscf/lasci.py", line 1021, in kernel
    self.ci, h2eff_sub, veff = _kern(mo_coeff=mo_coeff, ci0=ci0, verbose=verbose, \
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/lgagliardi/jangidbhavnesh/Apps/Trash/newdev/mrh/my_pyscf/mcscf/lasscf_async/lasscf_async.py", line 64, in kernel
    keyframe.count_common_orbitals (las, kf1, kfi)
  File "/project/lgagliardi/jangidbhavnesh/Apps/Trash/newdev/mrh/my_pyscf/mcscf/lasscf_async/keyframe.py", line 178, in count_common_orbitals
    u, svals, vh = orbital_block_svd (las, kf1, kf2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/lgagliardi/jangidbhavnesh/Apps/Trash/newdev/mrh/my_pyscf/mcscf/lasscf_async/keyframe.py", line 144, in orbital_block_svd
    u_virt, svals_virt, vh_virt = linalg.svd (s1)
                                  ^^^^^^^^^^^^^^^
  File "/software/python-anaconda-2023.09-el8-x86_64/lib/python3.11/site-packages/scipy/linalg/_decomp_svd.py", line 131, in svd
    raise LinAlgError("SVD did not converge")

Input file: 
**import numpy as np
from pyscf import gto, scf, mcscf
from pyscf.lib import chkfile
from pyscf.data import nist
from pyscf.mcscf import avas
from mrh.my_pyscf.mcscf.lasscf_o0 import LASSCF
from mrh.my_pyscf.mcscf import lasscf_async as asyn
from mrh.my_pyscf import lassi
from pyscf.tools import molden

basis={'C': 'def2SVP','H': 'def2SVP','S': 'def2TZVP', 'Fe': 'def2TZVP'}

mol = gto.Mole()
mol.atom = 'fe2s2.xyz'
mol.spin = 10
mol.charge = -2
mol.max_memory = 100000
mol.basis = basis
mol.verbose = 4
mol.build()

mf=scf.ROHF(mol).newton().density_fit()
mf.chkfile = 'fe2s2.chk'
mf.init_guess = 'chk'
mf.max_cycle = 200
mf.conv_tol = 1e-11
mf.kernel()

assert (mf.converged)

ncas_avas, nelecas_avas, mo_coeff = avas.kernel(mf, ['Fe 3d', 'Fe 4d'], minao=mol.basis)
molden.from_mo(mol, 'avas.molden', mo_coeff)

las = asyn.LASSCF(mf, (10, 10),((5,0),(5, 0)),spin_sub=(6,6))
mo_list = [x for x in range(89, 109)]
mo_coeff = las.sort_mo (mo_list, mo_coeff)
guess_mo_coeff = las.set_fragments_(([0], [5]), mo_coeff)

molden.from_mo(mol, 'guess.molden', guess_mo_coeff)

las = lassi.spaces.spin_shuffle(las)
las.weights = [1.0/las.nroots,]*las.nroots
las.max_cycle_macro = 200
las.kernel(guess_mo_coeff)

**

**Comment by MatthewRHermes** [comment]
Please update. In recent commits I have a whole handler wrapped around that svd call.
