### ISSUE TITLE
LASSCF output printout has an error.

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#111]
Raised by: Noah

/project/lgagliardi/shared/Apps/pyscf
/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/pyscf
When PYTHONPATH is set, it is recommended to load these plugins through the environment variable PYSCF_EXT_PATH
Traceback (most recent call last):
  File "input.py", line 43, in <module>
    las.kernel(mo)
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasci.py", line 1022, in kernel
    [self.ci](http://self.ci/), h2eff_sub, veff = _kern(mo_coeff=mo_coeff, ci0=ci0, verbose=verbose, \
  File "/project/lgagliardi/shared/Apps/mrh/my_pyscf/mcscf/lasscf_async/lasscf_async.py", line 111, in kernel
    [log.info](http://log.info/) ('LASSCF %s after %d cycles', ('not converged', 'converged')[converged], it+1)
  File "/project/lgagliardi/shared/Apps/pyscf/pyscf/lib/logger.py", line 136, in info
    flush(rec, msg, *args)
  File "/project/lgagliardi/shared/Apps/pyscf/pyscf/lib/logger.py", line 115, in flush
    rec.stdout.write(msg%args)
ValueError: I/O operation on closed file.

I think line 102 is closing the log, which would be inaccessible for further writing. 
https://github.com/MatthewRHermes/mrh/blob/master/my_pyscf/mcscf/lasscf_async/lasscf_async.py#L102

**Comment by MatthewRHermes** [comment]
Line 102 closes what should be different files. What is the input that led to this?

**Comment by JangidBhavnesh** [comment]
import sys
from pyscf import gto, scf, tools, dft, lib
from mrh.my_pyscf.mcscf.lasscf_async import LASSCF
from mrh.my_dmet import localintegrals, dmet, fragments
from mrh.my_pyscf import mcpdft

# Initialization
mol = gto.M()
mol.atom='''H -5.10574 2.01997 0.00000; H -4.29369 2.08633 0.00000; H -3.10185 2.22603 0.00000; H -2.29672 2.35095 0.00000'''
mol.basis='sto3g'
mol.verbose=4
mol.build()

# Mean field calculation
mf = scf.ROHF(mol).newton().run()


# Option-1: Perform LASSCF and then pass las object
# LASSCF Calculations
las = LASSCF(mf,(2, 2),(2, 2),spin_sub=(1, 1))
frag_atom_list = ([0, 1], [2, 3])
mo0 = las.set_fragments_(frag_atom_list)
elas = las.kernel(mo0)[0]

**Comment by JangidBhavnesh** [comment]
Once this is pushed in. can you please update the shared mrh as well ?

Thanks

**Comment by MatthewRHermes** [comment]
In the meantime, this won't happen at all if you specify an output file name.
