### ISSUE TITLE
LAS-PDFT density matrices

### ISSUE THREAD

**Issue by MatthewRHermes** [MatthewRHermes/mrh#113]
https://github.com/MatthewRHermes/mrh/blob/cb590127abb7b96d6accb7cbdb49de1227a1cb1f/my_pyscf/mcpdft/laspdft.py#L225-L237

https://github.com/MatthewRHermes/mrh/blob/cb590127abb7b96d6accb7cbdb49de1227a1cb1f/my_pyscf/mcpdft/laspdft.py#L169-L188

This builds _all_ of the LASSI 1- and 2-RDMs, even if the user only asks for 1 or a few states. This is a waste of time and memory.

**Comment by MatthewRHermes** [comment]
PR #115 may have fixed this, but I'm leaving it open until we are 100% sure.

**Comment by JangidBhavnesh** [comment]
There is big memory hike during below mentioned step whenever it is being used for the rdm generations during the PDFT steps. However the same steps has been called from the LASSI diagonalization, but during that step there isn't big memory uses.

https://github.com/MatthewRHermes/mrh/blob/dev/my_pyscf/lassi/op_o1.py
#L1505-L1507

   def _crunch_all_(self):
        for row in self.exc_1d: self._crunch_env_(self._crunch_1d_, *row)
        for row in self.exc_2d: self._crunch_env_(self._crunch_2d_, *row)
