### ISSUE TITLE
cmake problem with cint.h

### ISSUE THREAD

**Issue by hebrewsnabla** [MatthewRHermes/mrh#12]
In `mrh/lib/CMakeLists.txt`, only two directories are included
```
include_directories(${PYSCFLIB})
include_directories(${PYSCFLIB}/deps/include)
```
But in PySCF's CMakeLists.txt, there're three
```
include_directories(${PROJECT_SOURCE_DIR})
include_directories(${PROJECT_SOURCE_DIR}/deps/include)
include_directories(${CMAKE_INSTALL_PREFIX}/include)
```
The difference is that when I install libcint manually in a location other than `${PYSCFLIB}/deps`, and call cmake by
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/path/to/libcint ..
```
PySCF compilation works well, but mrh could not be compiled. An error like `cint.h: No such file or directory` will occur.

I think one solution is to add `include_directories(${CMAKE_INSTALL_PREFIX}/include)` in  `mrh/lib/CMakeLists.txt`. Maybe there's another way, like using command line options of cmake, but I'm not familiar with that. Do you have any suggestion for resolving this problem?

**Comment by MatthewRHermes** [comment]
Fixed by PR #15
