### ISSUE TITLE
Potential bug in LASSI rdm calculation

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#127]
I am doing LASSI-PDFT, for which I need RDMs from LASSI wavefunction. During that, I am getting this error.
/home/jangidbhavnesh/bin/mrh/lib/lassi/rdm.c:214: LASSIRDMdputSD2: Assertion `sidx < SDsrc_size'

I am using commit 538e93a8cc7d8bc070057c0651427d7c3da89d45
Input file: https://github.com/MatthewRHermes/mrh/blob/master/examples/laspdft/c2h4n4_si_laspdft.py

**Comment by MatthewRHermes** [comment]
I'm not getting that error on that commit. Do you need to recompile the mrh C libraries?

**Comment by JangidBhavnesh** [comment]
This function /home/jangidbhavnesh/bin/mrh/lib/lassi/rdm.c:214: LASSIRDMdputSD2: Assertion `sidx < SDsrc_size' failed.

doesn't work if I have more than 32 threads.

**Comment by JangidBhavnesh** [comment]
It's working now.

Thanks.
