### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by tbhuber** [MatthewRHermes/mrh#13]
I was interested in using mrh with pyscf. I tried installing 'mrh' on my system using cmake and obtained the following errors(see end of post). I was able to fix the build by doing the following. I figured I would post this in case you wanted to include this fix in the documentation or implement in the cmake.

- Error 1:  "/home/z1862058/src/pyscf/pyscf/__init__.py", line 98,...
I replaced python with python3 in  mrh/lib/CMakeLists.txt
set (PYTHON_EXECUTABLE "python3")

- Error 2: #include "build/config.h"
cmake 'forgot' to create config.h file in the build directory. I simply created an empty file in the lib build. 
'$touch config.h'

- Error 3:
I then executed 'make'  and noted that the code needed includes files from the source in pyscf.
I simply moved pyscf into mrh directory and defined the corresponding PYTHONPATH.
I then needed to create links to the required .h files in mrh/lib directory.

ln -s  /home/z1862058/src/mrh/pyscf/pyscf/lib/build/deps/src/libcint-build/include/cint.h
ln -s /home/z1862058/src/mrh/pyscf/pyscf/lib/vhf
ln -s /home/z1862058/src/mrh/pyscf/pyscf/lib/np_helper
ln -s /home/z1862058/src//mrh/pyscf/pyscf/lib/gto

Rebuilt everything and build completed successfully.

cd ../mrh/lib/build
rm -rf *
cmake ..
touch config.h
make

~Tim

"cmake .. "error

[z1862058@gaea build]$ cmake ..
-- A library with BLAS API found.
-- A library with LAPACK API found.
Traceback (most recent call last):
  File "", line 3, in 
  File "/home/z1862058/src/pyscf/pyscf/__init__.py", line 98, in 
    numpy.__version__)
SystemError: You're using an old version of Numpy (1.7.1). It is recommended to upgrade numpy to 1.8.0 or newer.
You still can use all features of PySCF with the old numpy by removing this warning msg. Some modules (DFT, CC, MRPT) might be affected because of the bug in old numpy.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/z1862058/src/mrh/lib/build

"make" error

[z1862058@gaea build]$ make
[ 20%] Built target clib_mrh_csf
[ 40%] Built target clib_mrh_fsucc
[ 60%] Building C object CMakeFiles/clib_mrh_pdft.dir/nr_numint.c.o
/home/z1862058/src/mrh/lib/nr_numint.c:26:26: fatal error: build/config.h: No such file or directory
 #include "build/config.h"
                          ^
compilation terminated.
make[2]: *** [CMakeFiles/clib_mrh_pdft.dir/nr_numint.c.o] Error 1
make[1]: *** [CMakeFiles/clib_mrh_pdft.dir/all] Error 2
make: *** [all] Error 2

**Comment by MatthewRHermes** [comment]
Thanks for sharing.  All the dependencies including config.h are supposed to be located by this part of CMakeLists.txt:
```
# Find the PySCF "library" directory
set (PYTHON_EXECUTABLE "python")
execute_process(
  COMMAND "${PYTHON_EXECUTABLE}" -c "if True:
    import os
    from pyscf import lib
    print (os.path.dirname (lib.__file__))"
  OUTPUT_VARIABLE PYSCFLIB
  OUTPUT_STRIP_TRAILING_WHITESPACE)
include_directories(${PYSCFLIB})
include_directories(${PYSCFLIB}/deps/include)
link_directories(${PYSCFLIB})
```
provided that one has installed PySCF by downloading from source and compiling locally, as mentioned in the readme. But I am admittedly a CMake novice, and I see your point about "python3".

**Comment by hebrewsnabla** [comment]
I've built PySCF from source and can confirm the location of `lib` by manually running
```
wsr@yoga:~/mrh/lib/build> python -c "if True:
    import os
    from pyscf import lib
    print (os.path.dirname (lib.__file__))"
/home/wsr/pyscf/pyscf/lib
```
And I do have a `config.h` there
```
wsr@yoga:~/mrh/lib/build> ls ~/pyscf/pyscf/lib/build/config.h
/home/wsr/pyscf/pyscf/lib/build/config.h
```
However it still fails when make
```
[ 70%] Building C object CMakeFiles/clib_mrh_pdft.dir/nr_numint.c.o
/home/wsr/mrh/lib/nr_numint.c:26:10: fatal error: build/config.h: No such file or directory
   26 | #include "build/config.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/clib_mrh_pdft.dir/build.make:76: CMakeFiles/clib_mrh_pdft.dir/nr_numint.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: CMakeFiles/clib_mrh_pdft.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
It seems cmake did not get the `PYSCFLIB` variable successfully, as I add a `message` to print out it and find it's empty.

**Comment by MatthewRHermes** [comment]
@hebrewsnabla Could you pull [9ed0ba3] (current master branch) and give me the cmake output that you get?

**Comment by MatthewRHermes** [comment]
Also, I just made a new branch ("cmakefiles") which tries to let you set PYSCFLIB on the command line:
```
cmake -DPYSCFLIB=/full/path/to/pyscf/lib ..
```

**Comment by hebrewsnabla** [comment]
> @hebrewsnabla Could you pull [[9ed0ba3](https://github.com/MatthewRHermes/mrh/commit/9ed0ba3925b897d5c561ad60710820f4a423ebba)] (current master branch) and give me the cmake output that you get?

It works. And the make step works fine.
```
-- Found Python: /usr/bin/python3.8 (found version "3.8.13") found components: Interpreter
CMake Debug Log at CMakeLists.txt:61 (execute_process):
  Variable "Python_EXECUTABLE" was accessed using READ_ACCESS with value
  "/usr/bin/python3.8".


CMake Debug Log at CMakeLists.txt:61 (execute_process):
  Variable "PYSCFLIB" was accessed using MODIFIED_ACCESS with value
  "/home/wsr/pyscf/pyscf/lib".


CMake Debug Log at CMakeLists.txt:68 (include_directories):
  Variable "PYSCFLIB" was accessed using READ_ACCESS with value
  "/home/wsr/pyscf/pyscf/lib".


CMake Debug Log at CMakeLists.txt:69 (include_directories):
  Variable "PYSCFLIB" was accessed using READ_ACCESS with value
  "/home/wsr/pyscf/pyscf/lib".


CMake Debug Log at CMakeLists.txt:70 (link_directories):
  Variable "PYSCFLIB" was accessed using READ_ACCESS with value
  "/home/wsr/pyscf/pyscf/lib".


CMake Debug Log at CMakeLists.txt:106 (target_link_libraries):
  Variable "PYSCFLIB" was accessed using READ_ACCESS with value
  "/home/wsr/pyscf/pyscf/lib".


-- Configuring done
-- Generating done
```

**Comment by hebrewsnabla** [comment]
> Also, I just made a new branch ("cmakefiles") which tries to let you set PYSCFLIB on the command line:
> 
> ```
> cmake -DPYSCFLIB=/full/path/to/pyscf/lib ..
> ```
> 
> Does it work for you?

This one works, too.

**Comment by MatthewRHermes** [comment]
Merged fix into "dev" and "master".
