### ISSUE TITLE
Question about `gen_g_hop` and testing `pdft_feff`

### ISSUE THREAD

**Issue by matthew-hennefarth** [MatthewRHermes/mrh#37]
See how this works to use github to ask questions. So in general, I have written out the kernel functions for generating $\Delta\cdot \mathbf{F}$ which have elements of
$$\left[\Delta \cdot \mathbf{F}\right]\_{pq} = \int \vec{\rho}^t_\Delta\mathbf{f}^\mathrm{ot}\frac{\partial \vec{\rho}}{\partial\gamma_{pq}}$$
and for the 4-body term as well [here](https://github.com/matthew-hennefarth/pyscf-forge/blob/20b45966da88803222434ccfe810f77a3585c145/pyscf/mcpdft/pdft_feff.py#L27-L158). It uses some generalization of the `veff` code which I extracted/reused. I was able to [test](https://github.com/matthew-hennefarth/pyscf-forge/blob/20b45966da88803222434ccfe810f77a3585c145/pyscf/mcpdft/test/test_pdft_feff.py#L125-L165) that the `lazy_kernel` and `kernel` functions agree using the same method as the `veff` code (I used the ao->mo for the 2-electron terms). What I want to do though is test that the $\Delta\cdot \mathbf{F}$ elements agree when you numerically differentiate the $V_{pq}$ and $v_{pqrs}$ elements and then contract with a density.

For testing `pdft_veff`, I generally understand what is happening [here](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L55-L57). The `gen_g_hop` gets the gradient, gradient update, hessian_update, and hessian_diag elements, right? Does g_all, in the orbital sector (ie `g_all[:ngorb]`) contain the 
$$F_{xy} - F_{yx}$$
where $F_{xy}$ is the generalized Fock matrix elements given the `eris` and `get_hcore()` in the current environment?

Regardless, you get the `x0` term which is the step in some direction. You then scale that term progressively smaller and checking to see if you get numerical convergence of the difference between the analytical and numerical derivative (summary of [these lines](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L73-L88)). I am a bit confused on what [`np.dot(g_all, x1)`](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L81) represents here mathematically (which is conflated with what exactly `g_all` is).

With that being said, how should I go about testing the `pdft_feff` terms numerically? I understand that you wrote the `EotOrbitalHessianOperator` and test this, but is there a simpler way of testing without having to copy a bunch of code from the [file](https://github.com/MatthewRHermes/mrh/blob/master/my_pyscf/mcpdft/pdft_feff.py)? You also discuss needing to use a "dressed `gen_g_hop`" object ([here](https://github.com/MatthewRHermes/mrh/blob/2662be46f61cf65b126006d3932aceaa8115e567/my_pyscf/mcpdft/pdft_feff.py#L143-L149)).

Lastly, I am a bit confused on what exactly `paaa_only` does for the `_ERIS` (see [these lines](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/pdft_veff.py#L103-L115)). If I understand correctly, you are adding the active space contribution of the HF potential to the HF potential core term? I know this is important since similar terms appear in the [`gen_g_hop`](https://github.com/pyscf/pyscf/blob/a27ddc77bcad42b0ee8707d93acc691fe9d51e5d/pyscf/mcscf/mc1step.py#L65-L70) code and the [`EotOrbitalHessianOperator`](https://github.com/MatthewRHermes/mrh/blob/2662be46f61cf65b126006d3932aceaa8115e567/my_pyscf/mcpdft/pdft_feff.py#L152-L155)

Any help would be appreciated, and let me know if you would rather me ask these questions via a different method of communication.

**Comment by MatthewRHermes** [comment]
> For testing `pdft_veff`, I generally understand what is happening [here](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L55-L57). The `gen_g_hop` gets the gradient, gradient update, hessian_update, and hessian_diag elements, right? Does g_all, in the orbital sector (ie `g_all[:ngorb]`) contain the Fxy−Fyx where Fxy is the generalized Fock matrix elements given the `eris` and `get_hcore()` in the current environment?

Yes. Furthermore, the remaining elements (`g_all[ngorb:]`) are gradients of the energy with respect to CI vector relaxations towards individual determinants:

$$\langle i|\hat{H}-E_0|0\rangle + \mathrm{h.c.}$$

> 
> Regardless, you get the `x0` term which is the step in some direction. You then scale that term progressively smaller and checking to see if you get numerical convergence of the difference between the analytical and numerical derivative (summary of [these lines](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L73-L88)). I am a bit confused on what [`np.dot(g_all, x1)`](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/test/test_pdft_veff.py#L81) represents here mathematically (which is conflated with what exactly `g_all` is).
> 

The product of a gradient with a step vector is an approximation to the energy difference after that step, which becomes exact in the limit of small step size with a definite constant of proportionality:

$$
\Delta f = f(1)\delta + \frac{1}{2}f(2)\delta^2 + \cdots 
$$

$$
\lim_{\delta\to 0} \frac{\Delta f - f(1)\delta}{\Delta f} = \frac{1}{2} \frac{f(2)}{f(1)}\delta
$$

In other words, there is an asymptotic plateau where if you halve the step size, you should also halve the relative error of the linear approximation. `np.dot (g_all, x1)` is $f(1)\delta$ and `seminum (x1)` is $\Delta f$. The version of this for second derivatives is

$$
\Delta (f') = f(2)\delta + \frac{1}{2}f(3)\delta^2 + \cdots 
$$

$$
\lim_{\delta\to 0} \frac{\Delta (f') - f(2)\delta}{\Delta (f')} = \frac{1}{2} \frac{f(3)}{f(2)}\delta
$$

but now the left and right-hand sides of the expression are both vectors. I compare them by evaluating the norm of the difference vector [here](https://github.com/MatthewRHermes/mrh/blob/2662be46f61cf65b126006d3932aceaa8115e567/tests/mcpdft/test_pdft_feff.py).
> With that being said, how should I go about testing the `pdft_feff` terms numerically? I understand that you wrote the `EotOrbitalHessianOperator` and test this, but is there a simpler way of testing without having to copy a bunch of code from the [file](https://github.com/MatthewRHermes/mrh/blob/master/my_pyscf/mcpdft/pdft_feff.py)? You also discuss needing to use a "dressed `gen_g_hop`" object ([here](https://github.com/MatthewRHermes/mrh/blob/2662be46f61cf65b126006d3932aceaa8115e567/my_pyscf/mcpdft/pdft_feff.py#L143-L149)).
> 

I'm sure there is a simpler way to implement because my implementation is incredible spaghetti. But regarding the "dressed `gen_g_hop`" comment, that is a reminder that what you call the "explicit" contribution to the Hessian is mappable to a CASSCF gradient with a modified Hamiltonian. That's what that entire conditional block of the initializer is about: if `incl_d2rho==False`, then only the terms in the Hessian-vector product which involve $\mathbf{f}^\mathrm{ot}$ are computed.

> Lastly, I am a bit confused on what exactly `paaa_only` does for the `_ERIS` (see [these lines](https://github.com/pyscf/pyscf-forge/blob/5e4236cf25a4b683ac053310243c929d76c2aeab/pyscf/mcpdft/pdft_veff.py#L103-L115)). If I understand correctly, you are adding the active space contribution of the HF potential to the HF potential core term? I know this is important since similar terms appear in the [`gen_g_hop`](https://github.com/pyscf/pyscf/blob/a27ddc77bcad42b0ee8707d93acc691fe9d51e5d/pyscf/mcscf/mc1step.py#L65-L70) code and the [`EotOrbitalHessianOperator`](https://github.com/MatthewRHermes/mrh/blob/2662be46f61cf65b126006d3932aceaa8115e567/my_pyscf/mcpdft/pdft_feff.py#L152-L155)

`vhf_c` by default is

$$
V_{pq} = v_{pqii}D_ii - \frac{1}{2}v_{qiip}D_ii = \frac{1}{2}v_{pqii}D_{ii} = v_{pqii} = \int v_{\Pi} \rho_{\mathrm{core}} \frac{\partial\rho}{\partial D_{pq}}
$$

If `paaa_only`, I hijack it to add

$$
V_{ai} = v_{aiuv}D_{uv} = \int v_{\Pi} \rho_{\mathrm{active}} \frac{\partial\rho}{\partial D_{ai}}
$$

$$
V_{aa} = v_{aauv}D_{uv} = \int v_{\Pi} \rho_{\mathrm{active}} \frac{\partial\rho}{\partial D_{aa}}
$$

$$
V_{ii} = v_{iiuv}D_{uv} = \int v_{\Pi} \rho_{\mathrm{active}} \frac{\partial\rho}{\partial D_{ii}}
$$

$$
V_{ia} = v_{iauv}D_{uv} = \int v_{\Pi} \rho_{\mathrm{active}} \frac{\partial\rho}{\partial D_{ia}}
$$

since these lead to contributions to the orbital gradient that, by default in PySCF, are computed using explicit two-electron interaction elements of the appropriate index patterns, which we have not computed if `paaa_only`. I think this would actually be a quicker algorithm for doing CASSCF orbital gradients themselves, if CASSCF didn't already need those ERIs anyway for orbital Hessians.

**Comment by matthew-hennefarth** [comment]
Okay, I think I understand a bit better, especially since I got it to sort of agree. What I have then is that 
$$\frac{\partial( V_{pq}D_{pq} + \frac{1}{2}v_{pqrs}d_{pqrs})}{\kappa_{xy}} = F_{xy} - F_{yx}$$
where
$$F_{xy} = V_{px}D_{py} + v_{pqrx}d_{pqry} + [\rho\cdot \mathbf{F}]\_{px}D\_{py} + [\rho\cdot \mathbf{F}]\_{pqrx}d\_{pqry}$$
The "explicit" and "implicit" terms. What I can do then, is compute analytically this derivative by doing 
```python
feff1, feff2 = mc.get_pdft_feff(mc.mo_coeff, mc.ci, paaa_only=True)
veff1, veff2 = mc.get_pdft_veff(mc.mo_coeff, mc.ci, incl_coul=False, paaa_only=True)
with lib.temporary_env(fcasscf, get_hcore=lambda:  feff1):
    g_feff, _, _, hdiag_feff = newton_casscf.gen_g_hop(fcasscf, mc.mo_coeff, mc.ci, feff2)
with lib.temporary_env(fcasscf, get_hcore=lambda: veff1):
    g_veff, _, _, hdiag_veff = newton_casscf.gen_g_hop(fcasscf, mc.mo_coeff, mc.ci, veff2)
```
I do it this way since I can't really add `feff2` and `veff2` since they are `_ERIS` objects (and addition is not well defined). I then set `g_all` and `hdiag_all` as
```python
g_all = g_feff + g_veff
hdiag_all = hdiag_feff + hdiag_veff
```
Though I am now unsure if I can just add `hdiag_feff` and `hdiag_veff`. Regardless, when I do this, I can then numerically differentiate
$$V_{pq}D_{pq} + \frac{1}{2}v_{pqrs}d_{pqrs} $$
by evaluating at the reference MO/CI and MO/CI + $\delta$, I get good agreement only when there are no core orbitals (`ncore=0`, or just for H2). When I go to LiH, I no longer get agreement (which has `ncore=1`). 

I am doing it this way since `feff1` and `feff2` pop-out as already being partially contracted (ie they are your Hessian-vector products) and can't really be interrogated in any other way (at least that I can think of). You can see my progress [here](https://github.com/matthew-hennefarth/pyscf-forge/blob/b8940187a07c19e23538f3f325b69b8960dd06f0/pyscf/mcpdft/test/test_pdft_feff.py#L68-L155) for testing.

**Comment by matthew-hennefarth** [comment]
> Though I am now unsure if I can just add `hdiag_feff` and `hdiag_veff`.

Just checked, and they agree with adding each term in the `_ERIS` object. Still not sure why the numerical evaluation doesn't decrease by 1/2 when there are core orbitals.

**Comment by MatthewRHermes** [comment]
On Friday we compared LiH (4e,3o) to LiH (2e,2o) and found that the differentiation fails for the latter but apparently not for the former. What happens if you take the LiH (2e,2o) wave function(s) and project it/them into the the LiH (4e,3o) Hilbert space? The `cistring` module has functions for doing things like this, even though I'm pretty sure it's equivalent to just pad the CI vector with zeros:

```
import numpy as np
from pyscf.fci import cistring
from pyscf.fci.direct_spin1 import _unpack_nelec

ncore_add = 1 # core orbitals to put in the active space
nvirt_add = 0 # virtual orbitals to put in the active space
ci_small = mc.ci # It'll get annoying if you have more than one CI vector here

# throat-clearing
norb_small = mc.ncas
norb_large = norb_small + ncore_add + nvirt_add
neleca_small, nelecb_small = _unpack_nelec (mc.nelecas)
neleca_large = neleca_small + ncore_add
nelecb_large = nelecb_small + ncore_add
ndeta_large = cistring.num_strings (norb_large, neleca_large)
ndetb_large = cistring.num_strings (norb_large, nelecb_large)
ci_large = np.zeros ((ndeta_large, ndetb_large), dtype=ci_small.dtype)

# Find the addresses of all determinants with fully-occupied core electrons
# I don't trust the behavior of this function with a range of length 0
addrs_a_core = cistring.sub_addrs (norb_large, neleca_large, range (ncore_add), ncore_add) if ncore_add else []
addrs_b_core = cistring.sub_addrs (norb_large, nelecb_large, range (ncore_add), ncore_add) if ncore_add else []

# Find the addresses of all determinants with fully-unoccupied virtual electrons
nvirt_range = range (ncore_add+norb_small,norb_large)
addrs_a_virt = cistring.sub_addrs (norb_large, neleca_large, nvirt_range, 0) if nvirt_add else []
addrs_b_virt = cistring.sub_addrs (norb_large, nelecb_large, nvirt_range, 0) if nvirt_add else []

# The intersection of these two address spaces is the address space of the smaller active space in the larger one.
if ncore_add and nvirt_add:
    addrs_a = np.intersect1d (addrs_a_core, addrs_a_virt)
    addrs_b = np.intersect1d (addrs_b_core, addrs_b_virt)
elif ncore_add:
    addrs_a, addrs_b = addrs_a_core, addrs_b_core
elif nvirt_add:
    addrs_a, addrs_b = addrs_a_virt, addrs_b_virt
else:
    raise RuntimeError ("whuddyadoin")

ci_large[np.ix_(addrs_a,addrs_b)] = ci_small[:,:]
```

Then all the f's and v's ought to be identical term-by-term.

**Comment by MatthewRHermes** [comment]
Having [looked at this myself](https://github.com/MatthewRHermes/pyscf-forge/blob/pdft_feff_debug/pyscf/mcpdft/test/test_pdft_feff.py#L103-L126), it looks like `energy_core` might be the problem somehow:
```
(pyscf) herme068@herme068:test$ python test_pdft_feff.py 
/home/herme068/anaconda3/envs/pyscf/lib/python3.7/site-packages/pyscf/dft/libxc.py:772: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '
Full Tests for pdft_feff
----------------------------------------------------------------------
mol = LiH state = Singlet fnal = ftLDA,VWN3 ncas = 2
eff1: -4.484549133295699
aaaa (ncas=2): [[[[ 0.19977412 -0.03598576]
   [-0.03598576  0.05526087]]

  [[-0.03598576  0.05526087]
   [ 0.05526087 -0.02894474]]]


 [[[-0.03598576  0.05526087]
   [ 0.05526087 -0.02894474]]

  [[ 0.05526087 -0.02894474]
   [-0.02894474  0.06524681]]]]
veff2.vhf_c (ncas=2): [[0.00374793 0.00157267]
 [0.00157267 0.00132303]]
feff2.vhf_c (ncas=2): [[0.05551745 0.02273624]
 [0.02273624 0.01368807]]
veff2.energy_core (ncas=2): 0.06549210899290742
feff2.energy_core (ncas=2): 1.1027722718342723
energy_core (ncas=2): 1.1682643808271798
MOs: 6, ncore: 1, ncas: 2, nelecas: (1, 1)
[0.5        0.64504058]
[0.5        1.01117394]
[0.5        0.76249662]
[0.5        0.15489007]
[0.5        0.37784289]
[0.5       0.5259212]
[0.5        0.65847538]
[0.5        0.76982305]
[0.5        0.86023152]
[0.5        0.92149352]
[0.5        0.95814844]
[0.5        0.97842798]
[0.5        0.98903878]
[0.5        0.99447284]
[0.5        0.99722437]
[0.5        0.99860911]
[0.5        0.99930378]
[0.5       0.9996517]
[0.5        0.99982583]
----------------------------------------------------------------------
mol = LiH state = Singlet fnal = ftLDA,VWN3 ncas = 3
eff1: -4.484549133295698
aaaa (ncas=2): [[[[ 0.19977412 -0.03598576]
   [-0.03598576  0.05526087]]

  [[-0.03598576  0.05526087]
   [ 0.05526087 -0.02894474]]]


 [[[-0.03598576  0.05526087]
   [ 0.05526087 -0.02894474]]

  [[ 0.05526087 -0.02894474]
   [-0.02894474  0.06524681]]]]
veff2.vhf_c (ncas=2): [[0.00374793 0.00157267]
 [0.00157267 0.00132303]]
feff2.vhf_c (ncas=2): [[0.05551745 0.02273624]
 [0.02273624 0.01368807]]
veff2.energy_core (ncas=2): 0.12722510876590137
feff2.energy_core (ncas=2): 2.149964734226756
energy_core (ncas=2): 2.2771898429926574
MOs: 6, ncore: 0, ncas: 3, nelecas: (2, 2)
[0.5       0.6648917]
[0.5      0.749354]
[0.5        0.84072247]
[0.5        0.92476315]
[0.5      0.984389]
[0.5        1.07434537]
[0.5        1.31380034]
[0.5        1.30091073]
[0.5        0.25557422]
[0.5        1.48212695]
[0.5        1.13604275]
[0.5        1.06062491]
[0.5       1.0295252]
[0.5        1.01467532]
[0.5        1.00732881]
[0.5        1.00366378]
[0.5        1.00183193]
[0.5      1.000916]
[0.5        1.00045801]
.
----------------------------------------------------------------------
Ran 1 test in 1.609s

OK
```
For the ncas=3 calculation, I did math on the `ppaa` array in the test script to generate the values that compare to the ncas=2 `vhf_c` and `energy_core` attributes. It worked perfectly for `vhf_c`, but not for `energy_core.` Note that it's not exactly a factor of 1/2 off, so even if I'm getting a convention wrong, there's still something else awry.

**Comment by MatthewRHermes** [comment]
Wait, no, when did the LiH (4e,3o) stop converging??????? argggghhh!

**Comment by matthew-hennefarth** [comment]
I think it could be the fact that `energy_core` is added each time we accumulate.

Take a look at these [line](https://github.com/matthew-hennefarth/pyscf-forge/blob/be8b18ddc46f7e2450e74af5e87477c8073db34e/pyscf/mcpdft/pdft_eff.py#L80-L84)
```python
  self.vhf_c += mo_coeff.conjugate().T @ ot.get_eff_1body(ao,
                                                       weight, vrho_c, non0tab=non0tab, shls_slice=shls_slice,
                                                       ao_loc=ao_loc,
                                                       hermi=1) @ mo_coeff
  self.energy_core = np.trace(self.vhf_c[:ncore, :ncore]) / 2
```
Each time we call the `_accumulate` we append to `self.vhf_c` which is fine. But then `self.energy_core` gets updated again. I think this is fine when `self.paaa_only=False`, but if `self.paaa_only=True` then the `self.vhf_c` also adds in `vhf_a`.
```python
if self.paaa_only:
    # 1/2 v_aiuv D_ii D_uv = v^ai_uv D_uv -> F_ai, F_ia
    # needs to be in here since it would otherwise be calculated using
    # ppaa and papa. This is harmless to the CI problem because the
    # elements in the active space and core-core sector are ignored
    # below.
    eff_rho_a = _contract_eff_rho(eff_Pi, rho_a)
    vhf_a = get_eff_1body(ot, ao, weight, eff_rho_a, non0tab=non0tab,
                          shls_slice=shls_slice, ao_loc=ao_loc, hermi=1)
    vhf_a = mo_coeff.conjugate().T @ vhf_a @ mo_coeff
    vhf_a[ncore:nocc, :] = vhf_a[:, ncore:nocc] = 0.0
    self.vhf_c += vhf_a
```
Then the next time we accumulate, we are not just accumulating over `vhf_c`, but also `vhf_c + vhf_a`? My logic here could be a bit off, but it might be something in the details of that. Perhaps it is better to just calculate `energy_core` differently?

**Comment by matthew-hennefarth** [comment]
I Got it!!

**Comment by matthew-hennefarth** [comment]
Okay, [here](https://github.com/matthew-hennefarth/pyscf-forge/blob/0a734f9f1d46caa48c6e432a0d324572c5b28d22/pyscf/mcpdft/test/test_pdft_feff.py#L101-L113) is the necessary commit info and lines. I fixed the `self.energy_core` with the [factor of 1/2 as you did](https://github.com/matthew-hennefarth/pyscf-forge/blob/0a734f9f1d46caa48c6e432a0d324572c5b28d22/pyscf/mcpdft/pdft_eff.py#L84).

**Comment by MatthewRHermes** [comment]
LGTM!
