### ISSUE TITLE
CSF Solver `max_memory` bug

### ISSUE THREAD

**Issue by matthew-hennefarth** [MatthewRHermes/mrh#43]
Using the `csf_solver` with spatial symmetry can raise an [exception](https://github.com/MatthewRHermes/mrh/blob/f1903816b461c41e8805d2377d4313863d215625/my_pyscf/fci/csf.py#L273-L275) for noting having enough memory in the `pspace` function, despite there being enough memory.

**Comment by MatthewRHermes** [comment]
TYVM!
