### ISSUE TITLE
Error in converging the lassis

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#55]
For the given input file, the LASSIS is not converging for default iterations. I increased the number of iterations to 1000, but the error still persist. Any suggestions to make it converge?

from pyscf import gto, scf, lib, mcscf, mcpdft
from mrh.my_pyscf.fci import csf_solver
from mrh.my_pyscf.mcscf.lasscf_o0 import LASSCF
from mrh.my_pyscf.tools.molden import from_lasscf
from mrh.my_pyscf import lassi

mol = gto.Mole()
mol.atom='''
6        0.000000    1.026841    0.000000
6        1.026841    0.000000    0.000000
6        0.000000   -1.026841    0.000000
6       -1.026841    0.000000    0.000000
1        0.000000    2.118166    0.000000
1        2.118166    0.000000    0.000000
1        0.000000   -2.118166    0.000000
1       -2.118166    0.000000    0.000000
'''

mol.charge = 0
mol.spin = 2
mol.basis = 'cc-pvdz'
mol.verbose = 4
mol.max_memory = 100000
mol.build()

mf = scf.ROHF(mol).density_fit()
mf.conv_tol=1e-12
mf.max_cycle = 200
mf.kernel()

las = LASSCF(mf, (3,3), (2,2),spin_sub=(1,1))
las.max_cycle_macro = 200
guess_mo = las.sort_mo([13, 14, 15, 20, 27, 30])
mo_coeff = las.localize_init_guess(([1, 2], [0, 3]), guess_mo)
las = lassi.states.spin_shuffle(las)
las.weights = [1.0/las.nroots,]*las.nroots
las.kernel(mo_coeff)

las1 = LASSCF(mf, (3,3), (2,2),spin_sub=(1,1))
las1.lasci_(las.mo_coeff)
lsi3 = lassi.LASSIS (las1)
lsi3.max_cycle_macro = 1000
lsi3.kernel()

********Output******
...
Cycle 995: max grad = 1.147491e-02 ; sigma = 2.527506e-01
Cycle 996: max grad = 1.147491e-02 ; sigma = 2.527506e-01
Cycle 997: max grad = 1.147491e-02 ; sigma = 2.527506e-01
Cycle 998: max grad = 1.147491e-02 ; sigma = 2.527506e-01
Cycle 999: max grad = 1.147491e-02 ; sigma = 2.527506e-01
Product_state fixed-point CI iteration NOT converged after 999 cycles
Debugging CI and gradient vectors...

**Comment by JangidBhavnesh** [comment]
Also, can we pass the level of local excitations inclusion in LASSIS?

**Comment by MatthewRHermes** [comment]
This is a strange active space choice. You have $|3\pi,2\pi^{\*},2\pi\rangle$ but no $3\pi^*$. If you read the debugging print out it tells you that the state $|0u0\rangle$ in this basis keeps trying to turn into the state $|u00\rangle$.

**Comment by JangidBhavnesh** [comment]
This system is cyclobutadiene, whose ground state has been shown to have diradical character. Which means for (6, 4) active space, 1DOMO + 2 SOMO, and 1 virtual orbital for each of them. Previous studies https://doi.org/10.1063/1.4998256  have shown that you need this type of active space. I also confirmed that by running the CASSCF in same active space (6, 4). 

from pyscf import gto, scf, mcscf, lib, mcpdft, mrpt
from pyscf.mcscf import avas


mol = gto.Mole()
mol.atom='''
6        0.000000    1.026841    0.000000
6        1.026841    0.000000    0.000000
6        0.000000   -1.026841    0.000000
6       -1.026841    0.000000    0.000000
1        0.000000    2.118166    0.000000
1        2.118166    0.000000    0.000000
1        0.000000   -2.118166    0.000000
1       -2.118166    0.000000    0.000000
'''

mol.charge = 0
mol.spin = 0
mol.basis = 'cc-pvdz'
mol.verbose = 4
mol.max_memory = 100000
mol.build()

mf = scf.RHF(mol).density_fit()
mf.conv_tol=1e-12
mf.max_cycle = 200
mf.kernel()

mc = mcscf.CASSCF(mf, 6, 4)
mc.conv_tol=1e-8
mc.fix_spin_(ss=0)
mc.max_cycle = 200
mc.kernel()

**Comment by MatthewRHermes** [comment]
There is a bug somewhere; the gradient computed by the Davidson diagonalizer is zero but the gradient computed in the fixed-point loop is nonzero. Also, the first two states of whichever fragment has only 1 electron keep switching places; IDK if that's related.

**Comment by JangidBhavnesh** [comment]
I see.

I idea is to find the fragment with 2 electron in DOMO, and a fragment with 2 electron in SOMO.  Therefore I used the (6,4) CAS active space as (3, 2) & (3, 2) active spaces in LAS. 

I will try with (2,2) & (4, 2) active space!
