### ISSUE TITLE
How to analyze the natural orb. occupation number or diradical character for LASSI state?

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#56]
from mrh.my_pyscf.mcscf.lasscf_o0 import LASSCF
from mrh.my_pyscf.tools.molden import from_lasscf
from mrh.my_pyscf import lassi

mol = gto.Mole()
mol.atom='''
6        0.000000    1.026841    0.000000
6        1.026841    0.000000    0.000000
6        0.000000   -1.026841    0.000000
6       -1.026841    0.000000    0.000000
1        0.000000    2.118166    0.000000
1        2.118166    0.000000    0.000000
1        0.000000   -2.118166    0.000000
1       -2.118166    0.000000    0.000000
'''

mol.charge = 0
mol.spin = 2
mol.basis = 'cc-pvdz'
mol.verbose = 4
mol.max_memory = 100000
mol.build()

mf = scf.ROHF(mol).density_fit()
mf.conv_tol=1e-12
mf.max_cycle = 200
mf.kernel()

las = LASSCF(mf, (2,2), (2,2), spin_sub=(1,1))
las.max_cycle_macro = 200
guess_mo = las.sort_mo([13, 14, 15, 20])
mo_coeff = las.localize_init_guess(([1, 2], [0, 3]), guess_mo)
las = lassi.states.spin_shuffle(las)
las.weights = [1.0/las.nroots,]*las.nroots
las.kernel(mo_coeff)

lsi = lassi.LASSIS(las).run()
lsi.analyze (state=[0,1,2])

State 0:
Neleca = [1. 1.]
Nelecb = [1. 1.]
Smult = [1.10199428 1.10199428]
State 1:
Neleca = [1. 1.]
Nelecb = [1. 1.]
Smult = [2.65877592 2.65877592]
State 2:
Neleca = [1. 1.]
Nelecb = [1. 1.]
Smult = [2.78023513 2.78023513]

How would I get the natural orb. occupation number or the diradical charter for state 0 and state 1?

**Comment by MatthewRHermes** [comment]
1. Pull dev
2.
```
from mrh.my_pyscf.tools.molden import from_lassi
from_lassi (lsi, 'foo.molden', state=0) # ground state
```
