### ISSUE TITLE
Passing of ci argument in lassi.LASSI()

### ISSUE THREAD

**Issue by dking072** [MatthewRHermes/mrh#72]
Passing the ci argument to las.LASSI() appears to do nothing. For example:

lsi.LASSI(las,ci="test")
lsi.kernel()

appears to just read from las.ci. It is only passing through lsi.kernel(ci=) that appears to work.

**Comment by MatthewRHermes** [comment]
huh, thanks for pointing this out, actually most of the kwargs of LASSI.__init___ do nothing. I'll clean this up.

**Comment by MatthewRHermes** [comment]
right ok, the reason for this is that I was extremely lazy here: https://github.com/MatthewRHermes/mrh/blob/b51243140bece355e5a75d78a04003bcdf57d4ab/my_pyscf/mcscf/lasci.py#L1474-L1481
Obviously this is no good.

**Comment by MatthewRHermes** [comment]
It should behave in the expected way now.
