### ISSUE TITLE
Question: Optimized LAS Orbitals

### ISSUE THREAD

**Issue by JangidBhavnesh** [MatthewRHermes/mrh#96]
Are the optimized las orbitals read from the chkfile in the localized or canonical basis?

**Comment by MatthewRHermes** [comment]
It reads the orbitals as they are written. I can't think of any circumstance in which the `dump_chk` function would be called with de-localized orbitals.

**Comment by JangidBhavnesh** [comment]
Okay,  So my next question is does LAS writes the localized or canonical orbitals in chkfile.

**Comment by MatthewRHermes** [comment]
> I can't think of any circumstance in which the dump_chk function would be called with de-localized orbitals.

**Comment by JangidBhavnesh** [comment]
Thank You.
